services:
  llmodel:
    image: ollama/ollama:latest
    container_name: ollama-container
    volumes:
      - vol:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - appnet
    deploy:
      resources:
        limits:
          memory: 8g
        reservations:
          memory: 4g
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull phi3 && wait"]
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  app:
    build:
      context: ./app
      dockerfile: streamlit.dockerfile
    container_name: app-container
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_HOST=http://ollama-container:11434
    depends_on:
      llmodel:
        condition: service_healthy
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge
    name: appnet

volumes:
  vol:
    name: vol


