apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30001 # Expose on a NodePort for local access (adjust if needed)
  type: NodePort