apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust based on `phi3` model size
  storageClassName: standard

