name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: tom-riddle-diary1
  SERVICE_NAME: my-app-with-sidecar
  REGION: us-central1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: tom-riddle-diary1
        service_account_key: my-app-with-sidecar
        export_default_credentials: true

    # Login to GCR
    - name: Authenticate to Google Cloud Registry
      run: gcloud auth configure-docker

    # Build and push main app
    - name: Build and Push Main App
      working-directory: ./app
      run: |
        # docker build -t gcr.io/$PROJECT_ID/main-app:latest .
        # docker push gcr.io/$PROJECT_ID/main-app:latest
        docker build -t us-central1-docker.pkg.dev/tom-riddle-diary1/repo/streamlit:latest -f streamlit.dockerfile .
        docker push us-central1-docker.pkg.dev/tom-riddle-diary1/repo/streamlit:latest

    # Build and push sidecar
    # - name: Build and Push Sidecar
    #   working-directory: ./sidecar
    #   run: |
    #     docker build -t gcr.io/$PROJECT_ID/sidecar:latest .
    #     docker push gcr.io/$PROJECT_ID/sidecar:latest

    # Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run services replace service.yaml \
          --region=$REGION \
          --project=tom-riddle-diary1

          