name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: tom-riddle-diary1
  SERVICE_NAME: my-app-with-sidecar
  REGION: us-central1

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCPSAKEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: tom-riddle-diary1

    - name: Authenticate to Google Cloud Registry
      run: gcloud auth configure-docker

    - name: Build and Push Main App
      working-directory: ./app
      run: |
        docker build -t gcr.io/tom-riddle-diary1/main-app:latest -f streamlit.dockerfile .
        docker push gcr.io/tom-riddle-diary1/main-app:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run services replace service.yaml \
          --region=$REGION \
          --project=tom-riddle-diary1

