name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCPSAKEY }}

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: tom-riddle-diary1

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/streamlit.dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/tom-riddle-diary1/streamlit-ollama-repo/streamlit:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy streamlit-ollama-service2 \
            --region us-central1 \
            --image us-central1-docker.pkg.dev/tom-riddle-diary1/streamlit-ollama-repo/streamlit:latest \
            --add-sidecar ollama/ollama:latest \
            --sidecar-name ollama-container \
            --sidecar-port 11434 \
            --sidecar-env "PORT=11434" \
            --sidecar-command "/bin/sh" \
            --sidecar-args "-c,ollama serve & sleep 5 && ollama pull phi3 && wait" \
            --sidecar-cpu 4 \
            --sidecar-memory 8Gi \
            --port 8501 \
            --env "OLLAMA_HOST=http://localhost:11434" \
            --cpu 2 \
            --memory 4Gi \
            --min-instances 1 \
            --max-instances 10 \
            --concurrency 80 \
            --timeout 3600s \
            --allow-unauthenticated \
            --service-account streamlit-ollama-service2-sa@tom-riddle-diary1.iam.gserviceaccount.com \
            --project tom-riddle-diary1